application: hoge
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

#default_expiration: "5h"

handlers:
  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: /favicon\.ico

  - url: /public
    static_dir: public

  - url: /admin/.*
    script: _go_app
    secure: always
    login: admin

  - url: /.*
    script: _go_app
    secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.map$
